api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "secure-jersey-transform"
uid = "3499b47a-717f-1c4e-bdfc-dd5c79ea3cbc68f0ac84"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/secure-jersey-transform.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
